Update document workflow

diff --git a/.github/workflows/document.yaml b/.github/workflows/document.yaml
--- a/.github/workflows/document.yaml
+++ b/.github/workflows/document.yaml
@@ -1,47 +1,38 @@
-name: Update Docs
-
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
-  workflow_dispatch:
   push:
-    branches: [main, master]
-    paths:
-      - "R/**"
+    paths: ["R/**"]
   pull_request:
-    branches: [main, master]
-    paths:
-      - "R/**"
+    paths: ["R/**"]
+  workflow_dispatch:
+
+name: Document
 
 jobs:
-  update-docs:
+  document:
     runs-on: ubuntu-latest
-    concurrency:
-      group: ${{ github.workflow }}-${{ github.ref }}
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-      - name: Setup R
-        uses: r-lib/actions/setup-r@v1
+      - uses: r-lib/actions/setup-r@v2
         with:
           use-public-rspm: true
 
-      - name: Install dependencies
-        uses: r-lib/actions/setup-r-dependencies@v1
+      - uses: r-lib/actions/setup-r-dependencies@v2
         with:
-          extra-packages: roxygen2
+          extra-packages: any::roxygen2
 
       - name: Document
-        run: Rscript -e 'roxygen2::roxygenise()'
+        run: roxygen2::roxygenise()
+        shell: Rscript {0}
 
-      - name: Commit changes
+      - name: Commit and push changes
         run: |
           git config --local user.name "$GITHUB_ACTOR"
           git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
           git add man/\* NAMESPACE
-          git commit -m 'Update docs' || echo "No modified docs."
-
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: ${{ github.ref }}
+          git commit -m 'Update documentation' || echo "No changes to commit"
+          git push origin || echo "No changes to commit"
